Complete dictionary homework
CoR0NaExTrA/TL_Practice_2024 pull request #2
Opened 2024-07-29 07:22 UTC by CoR0NaExTrA

2024-08-07 21:58 UTC, AlexPshkov requested changes
Задание абсолютно не выполнено

2024-08-07 21:58 UTC, AlexPshkov commented on OrderManager/OrderManager.sln
> -Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "OrderManager", "OrderManager\OrderManager.csproj", "{1B584ECD-582B-4925-9FD5-C4A4CF9ED163}"
Удали лишнее из ветки

2024-08-07 21:58 UTC, AlexPshkov commented on Dictionary/Dictionary/Program.cs
> +File.ReadAllLines()
Это че?)

2024-08-09 05:59 UTC, CoR0NaExTrA commented on Dictionary/Dictionary/Program.cs
> +File.ReadAllLines()
Sorry, мне пришлось делать новый репозиторий и те версии которые загружал удалились. Я не посмотрел что там нету кода.

2024-08-20 14:34 UTC, AlexPshkov approved these changes

2024-08-20 14:34 UTC, AlexPshkov commented on Dictionary/Dictionary/Dictionary.cs
> +void TryTranslate( Dictionary<string, string> d )
Почему у тебя где-то слово `dictionary` написано полность (в методе выше), а где-то просто `d`? Исправь везде на нормальные названия. Не стоит экономить на буквах

2024-08-22 06:31 UTC, merged